services:
  ebook-to-mindmap:
    image: ebook-to-mindmap-compose:latest
    build:
      context: ./
    # ports:
    #   - "5173:5173"
    container_name: ebook-to-mindmap-container
    restart: unless-stopped
    network_mode: 'host'
